version: "3"
services:
  proxy:
    container_name: proxy_nginx
    build: ./proxy
    image: proxy_nginx
    ports: 
      - 80:80
    restart: always

  db:
    container_name: mysql_backend
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /home/work/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: webapp_db
      MYSQL_ROOT_PASSWORD: 970716

  backend:
    container_name: backend_server
    build: ./backend
    image: backend:$BACKEND_COMMIT
    ports:
      - 7001:7001
    restart: always
    depends_on:
      - db
  
  qingyun:
    container_name: qingyun_middle
    build: ./middle
    image: qingyun:$MIDDLE_COMMIT
    ports:
      - 8000:8000
    restart: always

  blog:
    container_name: blog_front
    build: ./frontend
    image: blog:$BLOG_COMMIT
    ports:
      - 3000:3000
    restart: always
  
  home:
    container_name: web_home
    build: ./home
    image: home:$HOME_COMMIT
    ports:
      - 3001:3001
    restart: always

  
